from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


class ItineraryPDFService:


    @staticmethod
    def generate_pdf(trip, itinerary):

        buffer = BytesIO()


        doc = SimpleDocTemplate(

            buffer,

            pagesize=A4,

            rightMargin=50,

            leftMargin=50,

            topMargin=50,

            bottomMargin=50,

        )


        styles = getSampleStyleSheet()



        title_style = ParagraphStyle(

            "TitleStyle",

            parent=styles["Title"],

            alignment=TA_CENTER,

            fontSize=24,

            textColor=colors.HexColor("#2563EB"),

            spaceAfter=20,

        )


        heading_style = ParagraphStyle(

            "HeadingStyle",

            parent=styles["Heading2"],

            fontSize=16,

            textColor=colors.HexColor("#1D4ED8"),

            spaceBefore=15,

            spaceAfter=10,

        )


        normal_style = ParagraphStyle(

            "NormalStyle",

            parent=styles["BodyText"],

            fontSize=11,

            leading=16,

            textColor=colors.HexColor("#334155"),

        )


        story = []



        # Header

        story.append(

            Paragraph(

                "✈️ AI Smart Travel Planner",

                title_style

            )

        )


        story.append(

            Paragraph(

                "Your Personalized Travel Journey",

                normal_style

            )

        )


        story.append(
            Spacer(1,25)
        )



        # Trip Summary Card


        summary_data = [

            [
                "Trip Name",
                trip.trip_name
            ],

            [
                "Travel Dates",
                f"{trip.start_date} - {trip.end_date}"
            ],

            [
                "Travelers",
                str(trip.travelers)
            ],

            [
                "Budget",
                f"₹{trip.budget}"
            ],

            [
                "Transport",
                trip.transport
            ],

        ]



        table = Table(

            summary_data,

            colWidths=[1.5*inch,3.5*inch]

        )



        table.setStyle(

            TableStyle(

                [

                    (
                        "BACKGROUND",
                        (0,0),
                        (0,-1),
                        colors.HexColor("#DBEAFE")
                    ),


                    (
                        "GRID",
                        (0,0),
                        (-1,-1),
                        0.5,
                        colors.HexColor("#CBD5E1")
                    ),


                    (
                        "PADDING",
                        (0,0),
                        (-1,-1),
                        10
                    ),

                ]

            )

        )


        story.append(table)



        story.append(

            Spacer(1,30)

        )



        # Itinerary Content


        story.append(

            Paragraph(

                "🗺️ AI Generated Itinerary",

                heading_style

            )

        )



        clean_text = itinerary.replace(

            "#",

            ""

        )



        for line in clean_text.split("\n"):


            line=line.strip()


            if not line:

                continue



            story.append(

                Paragraph(

                    line,

                    normal_style

                )

            )


            story.append(

                Spacer(1,8)

            )



        story.append(

            Spacer(1,20)

        )



        # Footer


        story.append(

            Paragraph(

                "❤️ Have a safe and memorable journey!",

                heading_style

            )

        )


        story.append(

            Paragraph(

                "Generated by AI Smart Travel Planner",

                normal_style

            )

        )



        doc.build(story)



        pdf = buffer.getvalue()


        buffer.close()


        return pdf